### ISSUE TITLE
Chrono set to specific version

### ISSUE THREAD

**Issue by Mattsi-Jansky** [ChorusOne/rvcr#3]
Hey, thanks for publishing this it looks really helpful and I'm excited to give it a try. I hit a problem quickly though, `Cargo.toml` sets `chrono` to `version = "=0.4.20"`. The `=` forces that specific version and not any newer version so my project that uses `0.4.24` is not compatible. Specifically the error is:

```bash
❯ cargo add rvcr
    Updating crates.io index
      Adding rvcr v0.1.1 to dependencies.
    Updating crates.io index
error: failed to select a version for `chrono`.
    ... required by package `termibot v3.0.0 (/home/mattsi/dev/rust/termibot/bot)`
versions that meet the requirements `^0.4.24` are: 0.4.26, 0.4.25, 0.4.24

all possible versions conflict with previously selected packages.

  previously selected package `chrono v0.4.20`
    ... which satisfies dependency `chrono = "=0.4.20"` of package `rvcr v0.1.1`
    ... which satisfies dependency `rvcr = "^0.1.1"` of package `framework v0.1.0 (/home/mattsi/dev/rust/termibot/framework)`

failed to select a version for `chrono` which could resolve this conflict
```

Is there an explicit reason why newer `chrono` versions aren't supported? I had a quick look in the git history but couldn't see any documented reason.

**Comment by mksh** [comment]
Hi, thanks for the interest!

`chrono` authors chose to deprecate many methods in `chrono` versions 0.4.23+. Some other projects were using those methods, so this pin got into `Cargo.toml` template that was used for this project too.

However, for this crate use of `chrono` is really minimal, so there is no reason to pin.

Had created a PR https://github.com/ChorusOne/rvcr/pull/4 to unpin the minor version, let me know if it works for you -- will publish a new crate version soon if so.

**Comment by mksh** [comment]
New version published: https://crates.io/crates/rvcr/0.1.2
