### ISSUE TITLE
Filtering sensitive data

### ISSUE THREAD

**Issue by niclas-ahden** [ChorusOne/rvcr#9]
Would you be open to a basic, non-full-featured, implementation of [Filter Sensitive Data](https://benoittgt.github.io/vcr/#/configuration/filter_sensitive_data)?

I can't promise any timeline or that I'd do it at all, but I want to check with you before working on it.

Thanks!

**Comment by mksh** [comment]
Yes, absolutely, that would be much appreciated!

The approach we're currently using internally, is to put VCR files into encrypted cloud storage, and downloading them before running tests into gitignored location, so then auth secrets are never revealed in git history.

But, of course that approach is not ideal, and something close to original upstream feature would be very helpful.

**Comment by mksh** [comment]
Thank you for contribution @niclas-ahden ! I had added integration tests for the data filtering feature in PR https://github.com/ChorusOne/rvcr/pull/12, your review/comments are very welcome.
